export const GET_CARS_LOAD = "GET_CARS_LOAD";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAIL = "GET_CARS_FAIL";


export const GET_ONE_CAR_LOAD = "GET_ONE_CAR_LOAD";
export const GET_ONE_CAR_SUCCESS = "GET_ONE_CAR_SUCCESS";
export const GET_ONE_CAR_FAIL = "GET_ONE_CAR_FAIL";